### ISSUE TITLE
a mistake in 1.8 Form

### ISSUE THREAD

**Issue by tatesuke** [oneuijs/You-Dont-Need-jQuery#101]
1.8 Form -> Get index of e.currentTarget between .radio

```
// jQuery
$(e.currentTarget).index('.radio');

// Native
[].indexOf.call(document.querySelectorAll('.radio'), e.currentTarget);
```

I think jQuery code is ：
```
$('.radio').index(e.currentTarget);
```

**Comment by camsong** [comment]
Both are supported, if you like the second version, you and make a PR to add it as well.

**Comment by tatesuke** [comment]
Oh, it was true.
 I apologize for my lack of study...
