### ISSUE TITLE
Document height calculation seems inaccurate

### ISSUE THREAD

**Issue by hardfist** [oneuijs/You-Dont-Need-jQuery#113]
It seems that `$(document).height()` and  `document.documentElement.scrollHeight` behave differently according to this following demo 
http://codepen.io/hardfist/pen/oxaqrp?editors=1111

**Comment by camsong** [comment]
Yep, your are right, should be http://stackoverflow.com/a/1147768/1219343

**Comment by softwarespot** [comment]
I can submit a PR later on today

**Comment by camsong** [comment]
cool, that would be great
