### ISSUE TITLE
consider join https://github.com/you-dont-need org??

### ISSUE THREAD

**Issue by cht8687** [oneuijs/You-Dont-Need-jQuery#123]
Hi Cam,

Would you consider to transfer this project to https://github.com/you-dont-need ?
You will be the owner of the group. 

We admired this repo for quite a long time!

Please consider it!

Yours
Rob

**Comment by camsong** [comment]
Thanks for your invitation Bob, we already have a group to manage this repo, so no plan to transfer

**Comment by cht8687** [comment]
Thank you Cam for the reply!
If in future, you'd like to join, let me know!


cheers
Rob
