### ISSUE TITLE
Working with querySelector()'s null return.

### ISSUE THREAD

**Issue by Qix-** [oneuijs/You-Dont-Need-jQuery#13]
Something that's used often on our end is the `||` operator for `querySelector()` and `querySelectorAll()`. May be useful to include it as a possibility. It removes an if check or a ternary operator + double assignment.

This single thing helped a movement to remove jQuery from our agency's toolbelt at one point in time.

```javascript
var elements = [].slice.call(document.querySelectorAll('*') || []);
```

**Comment by camsong** [comment]
Good suggestion, updated the docs to clarify. https://github.com/oneuijs/You-Dont-Need-jQuery/commit/7d22a3fe895ed505092540a3681202bea9e082ff

**Comment by Qix-** [comment]
:+1: looks great!
