### ISSUE TITLE
something wrong with el.clientHeight

### ISSUE THREAD

**Issue by aimergenge** [oneuijs/You-Dont-Need-jQuery#135]
![image](https://cloud.githubusercontent.com/assets/13799160/22808953/f073618a-ef69-11e6-85bd-24136cfd3b9a.png)
I think it shouldn't contain border width.

I test it in chrome.

When border-box clientHeight means height - borderWidth
When content-box clientHeight means  height + padding

It looks like el.getBoundingRect().height is equal to el.offsetHeight.

**Comment by item4** [comment]
You're right. clientWidth/Height do not contain border. [[Reference]](https://developer.mozilla.org/en/docs/Web/API/Element/clientHeight)

**Comment by camsong** [comment]
@aimergenge Thanks for reporting.
