### ISSUE TITLE
`innerHTML` is bad! Maybe you should using ` insertAdjacentHTML`  👍 

### ISSUE THREAD

**Issue by xgqfrms-GitHub** [oneuijs/You-Dont-Need-jQuery#136]
# insertAdjacentHTML   👍 

# innerHTML 👎 

https://developer.mozilla.org/zh-CN/docs/Web/API/Element/insertAdjacentHTML

**Comment by camsong** [comment]
Yep, `insertAdjacentHTML` is good, can you make a PR to the english version?
