### ISSUE TITLE
Simulate `.one()` without jQuery

### ISSUE THREAD

**Issue by ifyouseewendy** [oneuijs/You-Dont-Need-jQuery#160]
Hi, thanks for making the repo. It helps a lot.

I didn't find a related topic of simulating `.one()` in the doc. I googled to find out [rofrol's answer in Only fire an event once?](https://stackoverflow.com/a/34325394/1331774), which works for me. Do you think it is something we need? I can make a PR on this.

```js
function addEventListenerOnce(target, type, listener) {
    target.addEventListener(type, function fn(event) {
        target.removeEventListener(type, fn);
        listener(event);
    });
}
```

**Comment by camsong** [comment]
Yep, PR please. thanks for the contribution
