### ISSUE TITLE
Complete the Utilities for jQuery

### ISSUE THREAD

**Issue by arcthur** [oneuijs/You-Dont-Need-jQuery#31]
Some utilities api will be complete for conversion.

- [x] Type related functions: type, inArray, isEmptyObject, isNumbic, isPlanObject, isWindow, isXMLDoc
- [x] FP functions: grep, each, map, merge, unique
- [x] Date function: now
- [x] Parse structures functions: parseHTML, parseJSON, parseXML
- [x] Others: globalEval, makeArray, proxy, support

**Comment by item4** [comment]
:+1:
