### ISSUE TITLE
Complete DOM Manipulation for jQuery

### ISSUE THREAD

**Issue by arcthur** [oneuijs/You-Dont-Need-jQuery#35]
Complete DOM Manipulation functions.

- [ ] clone
- [ ] wrap, unwrap
- [ ] detach, empty
- [ ] replaceWith, replaceAll

**Comment by jasonslyvia** [comment]
`clone()` has already been documented.

`detach()` acting exactly as `remove()` but keep jQuery data for future inserting, so if we don't use jQuery, we don't use `detach()`

`empty()` has been documented

`replaceAll()` acting like `replaceWith()` but keep jQuery data, for the aforementioned reason when don't have to deal with it

**Comment by jasonslyvia** [comment]
so current status should be 

- [x] clone
- [x] wrap, unwrap
- [ ] ~~detach~~
- [x] empty
- [x] replaceWith
- [ ] ~~replaceAll~~

**Comment by arcthur** [comment]
all complete! close issue
