### ISSUE TITLE
Question about compatibility

### ISSUE THREAD

**Issue by frankxin** [oneuijs/You-Dont-Need-jQuery#38]
Hi~  , I didn't get it , why the code can not support IE9 .
I didn't get the point.
Thank you.

**Comment by camsong** [comment]
Most of them should support IE9, but not fully tested, so use them on your own risk.

Some of the features you need to notice:
* `classList` started at  IE10
* `requestAnimationFrame` started at IE10, but can be easily poll-filled.

**Comment by frankxin** [comment]
I get it , cool~ 
Thank you~
