### ISSUE TITLE
Keeping same source in all translation

### ISSUE THREAD

**Issue by item4** [oneuijs/You-Dont-Need-jQuery#42]
Some PR update only some lang translation.

I think all source source code must be same.

How do you think about **building** readme with some script and seperated translation files?

For example..

```js
// en.js
{
util: {
title: "Utilities",
description: "",
contents: {
  isArray: { title: "isArray", description: "" }
}
...
}
```

and

```js
// isArray.js
// jQuery
$.isArray(range);

// Native
Array.isArray(range);
```

**Comment by camsong** [comment]
Nice idea to find a way to keep them sync automatically.
But this can be tough, firstly we should try to keep the docs easy maintain. Right now markdown is easy.

The JS are not easy enough, but still a good start, we should investigate on this further.

**Comment by item4** [comment]
We can check diff by travis-ci.

First, grep source code part and get count of each source part. If they have some difference, it was broken.

How about this?

**Comment by idiotWu** [comment]
How about keep code source in js files and using some directives to insert them? For example:

In markdown:
<pre>
#### code example:

```javascript
{{include 'src/a.js'}}
```
</pre>

In build tools:

```javascript
source.replace(/\{{2}include (['"])([^\1]+)\1\}{2}/g, (match, quote, src) => fs.readFileSync(src).toString());
```

In my view this will also be helpful for further testing :)

**Comment by Chocanto** [comment]
Some source code have comments that need to be translated. If you want to include them, it will not be possible to get internationalized comments (well... in reality, source code is a lot of time in English).
