### ISSUE TITLE
Ajax?

### ISSUE THREAD

**Issue by SubZane** [oneuijs/You-Dont-Need-jQuery#47]
Why is the document referring to using a 3rd party library instead of using native javascript?

**Comment by item4** [comment]
fetch is new native api.

[See this.](http://caniuse.com/#search=fetch)

**Comment by SubZane** [comment]
ah, missed that. Probably due to the lack of browser support :)

One could argue that it's better to use XMLHttpRequest since it has support

**Comment by camsong** [comment]
@item4 is right, Fetch is the new native API to replace XHR, it's simple and can handle request very well.

[fetch-ie8] is a polyfill to make fetch work in IE8+, [github/fetch](https://github.com/github/fetch) is another polyfill to work on IE9+. JSONP is kinda of hack, native api will not support it for sure.
