### ISSUE TITLE
missing implementation about `unique`

### ISSUE THREAD

**Issue by item4** [oneuijs/You-Dont-Need-jQuery#73]
See 932 line. What is `Sizzle's API`?

There is no impl, only misplaced text :(

**Comment by item4** [comment]
I think we can use `Set` of `innerHTML` of each element.

**Comment by camsong** [comment]
where is the line 932?

**Comment by item4** [comment]
@camsong https://github.com/oneuijs/You-Dont-Need-jQuery/blob/master/README.md#6.2 see `unique` util

**Comment by camsong** [comment]
@arcthur

**Comment by camsong** [comment]
We found that there are rare occasions that need to use `unique` when play with Virtual DOM, and this method rely on DOM manipulation heavily, so I will remove it for now
