### ISSUE TITLE
Put translation links on the top of the .md

### ISSUE THREAD

**Issue by Chocanto** [oneuijs/You-Dont-Need-jQuery#82]
Hey !

Now that this documentation is big (and well written), I think it would be a good idea to put translation links on the top of each readme instead of at the end.

It is easy for us to click on the readme file corresponding to the selected language in the respository files viewer, but for someone not familiar with it...

**Comment by camsong** [comment]
Yep, can you make a PR to update this in all translations?

**Comment by camsong** [comment]
I suggest to put it before `Table of Contents`
