### ISSUE TITLE
 "$.param" 这个方法又用什么替代呢？ 

### ISSUE THREAD

**Issue by na57** [oneuijs/You-Dont-Need-jQuery#83]
如题

**Comment by camsong** [comment]
`param` is odd in jQuery and behave differently in old versions. https://github.com/jquery/jquery/blob/70605c8e5655da996ebd395e3c43423daaa08d9c/src/serialize.js#L55

It's hard to create an equal replacement. The right way is to use `encodeURIComponent` on param `key` and `value` manually.
