### ISSUE TITLE
Keep translations list synchronized

### ISSUE THREAD

**Issue by Chocanto** [oneuijs/You-Dont-Need-jQuery#85]
I'm not really sure if more translations are coming, but it would be great to have a way to keep all translations list synchronized.

Maybe a test with travis should be possible.

**Comment by camsong** [comment]
It's doable to write a test cast to notify if a translation is out of date, but it's hard to sync them automatically nor can one fix the broken test if he/she doesn't understand that language.

We should keep investigating on this before found an feasible approach.
