### ISSUE TITLE
Is there a native solution for jq's .load?

### ISSUE THREAD

**Issue by Tedko** [oneuijs/You-Dont-Need-jQuery#88]
I have read the discussions on stackoverflow and seems there's still no good native solution to replace .load(). Then how do you guy deal with .load?

**Comment by camsong** [comment]
It's pretty easy to replace with fetch.

```js
// jquery
$(selector).load(url);

// native
fetch(url).then(data => data.text()).then(data => document.querySelector(selector).innerHTML=data)
```
