### ISSUE TITLE
$(document).ready

### ISSUE THREAD

**Issue by dillon9693** [oneuijs/You-Dont-Need-jQuery#92]
Not really an issue, more of an addition or "feature request", but... 

`$(document).ready(function(){...}); ` 

can be replaced by 

`document.addEventListener("DOMContentLoaded", function(event) {...});`

This is useful for making sure a DOM node is loaded before trying to access its elements or assign event listeners to it, etc.

Also, $(document).ready has more going on internally, but this could be considered a light replacement.

**Comment by camsong** [comment]
:clap:  Agreed, added https://github.com/oneuijs/You-Dont-Need-jQuery/commit/b52baa8e4ae235d91df4cdae1dc73b0a287b010a
